### ISSUE TITLE
Local snx_install.sh not working

### ISSUE THREAD

**Issue by mtodescato** [ruyrybeyro/chrootvpn#17]
Hi,

Since I can't download the snx_install.sh from the vpn I downloaded it separately.
Now I am trying to feed the snx script to installation script but it wont find it.
I've placed the snx_install.sh in the same directory of the chrootvpn installation, is It the right place?

**Comment by ruyrybeyro** [comment]
The script only replaced a downloaded file with a different version. It has been modified such that using the -l option, it expects both snx_install.sh and cshell_install.sh in the current working directory.
