### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by kristaps777** [ruyrybeyro/chrootvpn#19]
First time installation on Linux Mint 21.2 fails with:

Installing CShell
InstallChroot->chrootEnd: Something went wrong. Chroot unmounted. Fix it or delete /opt/chroot and run this script again.

Is there any way to determine what exactly went wrong?

**Comment by ruyrybeyro** [comment]
Many things can go wrong, notably transient communication errors or download delays. For the odd error that it can happen, if the action is repeated as the script suggests and it runs ok, no worth debugging it. 
Nonetheless, probably there is a download error or something else in all the activity log thread produced by the script, which can be captured to a file to be analyzed.
You can also run the script with the -d option for more debugging info. It can also be ran as ./vpn.sh log
The script is known to install in Mint 21.2, if an actual error please submit an issue. It needs both Internet access and access to the mobile portal to be installed with success.
