### ISSUE TITLE
This Portal is not supported on this server

### ISSUE THREAD

**Issue by diegodario88** [ruyrybeyro/chrootvpn#21]
Hey, thanks for putting effort into this project.

Could you please answer what needs to be done in order to resolve this error?

`This Portal is not supported on this server. Please contact your administrator for more information (14).`

This occur when trying to login at `https://vpn.example.com/Login/Login`

**Comment by ruyrybeyro** [comment]
hi,
The SSL VPN Web page has been disabled. You have to ask your organization for support/enabling it.

See:
https://support.checkpoint.com/results/sk/sk110272

"Some organization would like to have their users connecting to site only with Capsule Workspace applications and not through the Mobile Access web portal and have the portal login page obscured. They disable the SSL VPN with web browsers option in the Gateway object in the dashboard but once trying to browse to the portal web page they get an error: "Error: Access denied. This Portal is not supported on this server. Please contact your Administrator for more information (14) ""
