### ISSUE TITLE
Syntax error while installing cshell

### ISSUE THREAD

**Issue by CptOrange16** [ruyrybeyro/chrootvpn#27]
Hello

I'm trying to install the latest version (chrootvpn_1.96-1_all.deb) in a Debian GNU/Linux 12 (bookworm) system.

After running the _vpn.sh -i --vpn=..._  comand the script runs fine until it reaches a c_shell installation:

```
Processing triggers for ca-certificates (20210119) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
Installation successfull
Installing CShell
/root/cshell_install.sh: line 1: syntax error near unexpected token `newline'
/root/cshell_install.sh: line 1: `<html>'
InstallChroot->chrootEnd: Something went wrong. Chroot unmounted. Fix it or delete /opt/chroot and run this script again
```

**Comment by ruyrybeyro** [comment]
HI,

The script is not able to download a cshell_install.sh script from the firewall.

Assuming the command is correctly issued, either the Checkpoint on the other end is a version lower than  R80.10, or the Checkpoint mobile web portal has not been activated/licensed by the identity running it.

Regards

**Comment by CptOrange16** [comment]
Yes it seems that is the problem the content of the file is an html file that says page not found.

I'll get in contact with vpn people and see if they need to enable anything. It could also be a version issue, as i suspect it is very old
Thanks for the fast response

**Comment by ruyrybeyro** [comment]
If it is *very* old, this old answer of mine might still be useful for you https://unix.stackexchange.com/questions/450229/getting-checkpoint-vpn-ssl-network-extender-working-in-the-command-line
