### ISSUE TITLE
VPN can't connect on Kubuntu 24.04

### ISSUE THREAD

**Issue by khaerunsituncu** [ruyrybeyro/chrootvpn#31]
When I click connect a pop up only appears with a duration of 0 days as in the photo
![Screenshot_20240607_233121](https://github.com/ruyrybeyro/chrootvpn/assets/28919882/827da12c-4db7-41fa-a423-f196f1374011)

![image](https://github.com/ruyrybeyro/chrootvpn/assets/28919882/ab2f71b8-ba6e-4e9b-b6b7-015f770d81e8)

**the result of the command ./vpn.sh log**

07/06/2024 16:22:05.231 INFO [Log log] [Messaging]      Server fingerprint: LONG BONE EAT WENT LAND BUSY HOP HE FREE LACY MILT DEAF 
07/06/2024 16:22:05.231 INFO [Log log] [Messaging]      Automatic proxy replacement: true 
07/06/2024 16:22:05.231 INFO [Log log] [Messaging] Sending INIT_DATA_EX message: 
07/06/2024 16:22:05.231 INFO [Log log] [Messaging]      Allow only packets from sws: false 
07/06/2024 16:22:05.239 INFO [Log log] [CShell] Initialized successfully 
07/06/2024 16:22:05.557 INFO [CShellHTTPHandler proceedHandleRequest] Method name: get_is_connected 
07/06/2024 16:22:05.561 INFO [CShellHTTPHandler proceedHandleRequest] Method name: get_finished 
07/06/2024 16:22:45.273 INFO [Log log] [Messaging] Received DISCONNECTED message, Error 32: Cannot establish connection to SSL Network Extender gateway. Try to reconnect. 
07/06/2024 16:22:45.274 INFO [CpComponent run] Received 'Disconnect' message from SNX:
 ID: 32 MSG:Cannot establish connection to SSL Network Extender gateway. Try to reconnect. 
07/06/2024 16:22:45.274 INFO [TunnelChecker stop] stop(true) 
07/06/2024 16:22:45.274 WARNING [TunnelChecker disconnectTunnel] Can't disconnect tunnel, client director is not defined. 
07/06/2024 16:22:45.274 WARNING [TunnelChecker stop] Can't stop disconnect checker, processed handle is not defined. 
07/06/2024 16:22:45.612 INFO [CShellHTTPHandler proceedHandleRequest] Method name: Uninitialize 
07/06/2024 16:22:45.612 INFO [TunnelChecker stop] stop(true) 
07/06/2024 16:22:45.612 WARNING [TunnelChecker disconnectTunnel] Can't disconnect tunnel, client director is not defined. 
07/06/2024 16:22:45.612 WARNING [TunnelChecker stop] Can't stop disconnect checker, processed handle is not defined. 
07/06/2024 16:22:45.617 INFO [CShellHTTPHandler proceedHandleRequest] Method name: stop 
07/06/2024 16:22:45.617 INFO [TunnelChecker stop] stop(true) 
07/06/2024 16:22:45.617 WARNING [TunnelChecker disconnectTunnel] Can't disconnect tunnel, client director is not defined. 
07/06/2024 16:22:45.617 WARNING [TunnelChecker stop] Can't stop disconnect checker, processed handle is not defined.

**Comment by ruyrybeyro** [comment]
This issue is related to the Checkpoint server side. Please open a ticket with your local network services team and provide them with the error details. 

This may be connected to the information found in Check Point Secure Knowledge https://support.checkpoint.com/results/sk/sk106339

I apologize for not being able to assist further.
