### ISSUE TITLE
Can't execute in OpenSuse Tumbleweed

### ISSUE THREAD

**Issue by Abner97** [ruyrybeyro/chrootvpn#37]
I'm trying to execute your script in OpenSuse TUmbleweed but i receive this output

ID=opensuse-tumbleweed
ID_LIKE=opensuse suse
PreCheck->getDistro: Only Debian, RedHat, ArchLinux, SUSE, Gentoo, Slackware, Void, Deepin, Kwort, Pisi, KaOS,NuTyx and Clear Linux family distributions supported

**Comment by ruyrybeyro** [comment]
Added a patch for proper OpenSUSE detection.
