### ISSUE TITLE
cshell_install.sh failed to update certificate

### ISSUE THREAD

**Issue by furqon** [ruyrybeyro/chrootvpn#6]
Hi @ruyrybeyro thank you for your effort in making this wrapper.

I already succeeded using your script to connect to the vpn. But after the fiest login it always failed to connect to the vpn. When trying to connect it always ask to  update the Mobile Access Portal Agent using cshell_install.sh
![Screenshot from 2022-10-08 19-41-05](https://user-images.githubusercontent.com/446747/194986767-2ca62ae7-0447-4771-bbee-8013a5584b66.png)

At first if tailed to update because of the path to certificate is different
![Screenshot from 2022-10-08 19-58-22](https://user-images.githubusercontent.com/446747/194985418-f8cc43a3-e10b-49a6-aa66-e3ff50f2c4fd.png)
After updating cshell_install to the path that your wrapper located I have another problem
![image](https://user-images.githubusercontent.com/446747/194985566-32f18149-81c6-41e5-9be0-e494ed92e22b.png)

Do you know ho to fix this? 
I'm using ubuntu 22.04

Best regards and thank you

**Comment by ruyrybeyro** [comment]
hi @furqon,

Forgot in the README to say how to launch it, added it now.

You don't need to deal with cshell_install.sh and snx_install.sh install, the script does that for you. Afer a reboot, for putting up the service, you run:

vpn.sh start

You can also add for your /etc/sudoers the line, depending on  vpn.sh location:

sofia ALL=(ALL:ALL) NOPASSWD: /usr/bin/vpn.sh
or
sofia ALL=(ALL:ALL) NOPASSWD: /usr/local/bin/vpn.sh

Regards

**Comment by furqon** [comment]
thank you, it work!

**Comment by ruyrybeyro** [comment]
@furqon  deleted your image from the post, I was able to reconstruct your web portal URL with public information using Google.

**Comment by furqon** [comment]
thank you very much @ruyrybeyro
