### ISSUE TITLE
Secure Connection Failed

### ISSUE THREAD

**Issue by rodrigofbm** [ruyrybeyro/chrootvpn#8]
Hi. I tried to run it but I'm facing that `Secure Connection Failed` error
```
doing first restart
non-network local connections being added to access control list
CShell stopped
Trying to start it again...
LAUNCHER> Starting CShell...
LAUNCHER> CShell Started
open browser at https://[VPN_HOST] to login/start  VPN

Accept localhost certificate anytime visiting https://localhost:14186/id
```

After open https://localhost:14186/id and accept the "risks" I've tried to open the https://[VPN_HOST] url on Firefox but I got the `Secure Connection Failed` message. Can you help me?

**Comment by ruyrybeyro** [comment]
The script being able to download and install SNX and the CShell agent *seems* to imply the VPN web portal is running, but it is not 100% certain. 

Nevertheless, the web Mobile Access Portal should open even without any software installed on the client side *if the service is running*.  The other procedures are to ensure a successful VPN session establishment.  

Are you able the URL  from another browser or another machine? Is the certificate VPN certificate itself well formed? Have you already used it in the past? Are you able to open it from a Windows host? Others persons are using it?

PS if you send me offline the actual address to my email, ruyrybeyro at gmail dot com, I can say something more specific.

**Comment by rodrigofbm** [comment]
@ruyrybeyro 

I'm using Debian 11. On Windows, even connected, I cannot open the https://[VPN_HOST]. Maybe the host url that I have is not the  Mobile Access Portal :/

**Comment by ruyrybeyro** [comment]
what does a wget https://xxxxx say?
